#!/bin/sh

# CDSB - Prepare for Installation of Cadence products on FreeBSD.
# Copyright (C) 2008 Zhang Liang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Email: meitolake@gmail.com

PATH="/bin:/usr/bin:$PATH"; export PATH

GetPath() (
    cd "`dirname "$1"`" && pwd
)

EchoN() {
    echo -n "$*"
}

DoInstPatch="`GetPath "$0"`/do_install.tcl.patch"
EchoN 'Please enter Synopsys Installer installation directory: '
read InstPath
DoInst="$InstPath/install_bin/do_install.tcl"
DotDoInst="$InstPath/install_bin/.do_install.tcl"
if [ -f "$DoInst" ]; then
    if [ ! -f "$DotDoInst" ]; then
	mv "$DoInst" "$DotDoInst"
	cp "$DoInstPatch" "$DoInst"
    fi
    echo 'Finish! '
else
    echo "Error: $InstPath not a Synopsys Installer installation directory. "
fi
